name: Deploy ALONE Music Bot

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Clone repository
    - name: Clone repository
      run: |
        git clone https://github.com/madarchodsnsnd/V.git
        cd V
        
    # Step 2: Install dependencies
    - name: Install system packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y unzip ffmpeg python3-pip
        
    # Step 3: Extract ALONE.210 (exact filename)
    - name: Extract bot files
      run: |
        if [ -f "ALONE.210" ]; then
          unzip ALONE.210 -d ALONE
          cd ALONE
        else
          echo "Error: ALONE.210 file not found!"
          echo "Contents of current directory:"
          ls -la
          exit 1
        fi
        
    # Step 4: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    # Step 5: Install requirements
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "Warning: requirements.txt not found, continuing anyway"
        fi
        
    # Step 6: Run the bot
    - name: Start the bot
      run: |
        python3 -m ALONE || python3 ALONE.py || python3 main.py || python3 -m alone
        
    # Keep workflow running
    - name: Keep alive
      run: |
        while true; do sleep 60; done
