name: Deploy ALONE Music Bot

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Clone repository
    - name: Clone V repository
      run: |
        git clone https://github.com/madarchodsnsnd/V.git
        cd V/ALONE
        
    # Step 2: Install system dependencies
    - name: Install required packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3-pip ffmpeg
        
    # Step 3: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    # Step 4: Install Python dependencies
    - name: Install requirements
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    # Step 5: Run the bot (assuming config is in files)
    - name: Start ALONE Music Bot
      run: |
        python3 -m Alone
        
    # Keep the workflow running
    - name: Keep alive
      run: |
        while true; do sleep 60; done
